CREATE TABLE [dbo].[User]
(
	[Id] NVARCHAR(128) PRIMARY KEY,
	[FirstName] NVARCHAR(50) NOT NULL,
	[LastName] NVARCHAR(50) NOT NULL,
	[EmailAddress] NVARCHAR(256) NOT NULL,
	[CreatedData] DATETIME2 NOT NULL DEFAULT getutcdate()
)
